baseURL = "https://www.samatkinson.com"
languageCode = "en-us"
title = "Samba codes"
theme="archie"
copyright = "© Sam Atkinson"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


paginate=3 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "node/react/kotlin/java/other"
	mathjax = false # enable MathJax support
	katex = false # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/samberic/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/samba_codes/"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/samatkinson/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3